// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw34-wqv9FOVSXbZVots8xciyxE9gNSgo',
    appId: '1:304414671121:android:6cb4462e2b1e924af54cb0',
    messagingSenderId: '304414671121',
    projectId: 'app-team2-2',
    storageBucket: 'app-team2-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCphBoft9JynvpBekwNOfef857oUOHEKOE',
    appId: '1:304414671121:ios:8507965348c50852f54cb0',
    messagingSenderId: '304414671121',
    projectId: 'app-team2-2',
    storageBucket: 'app-team2-2.firebasestorage.app',
    androidClientId: '304414671121-37e8ghndqcot5aqs4o8krfrvbsk6enok.apps.googleusercontent.com',
    iosClientId: '304414671121-s1mofldragu61jte6mc6igau83oqoabn.apps.googleusercontent.com',
    iosBundleId: 'com.anypost.app',
  );

}